version: "3"

services:
  frontend:
    container_name: smart_elevator_frontend_container
    image: smart_elevator_frontend_image
    build:
      context: .
    ports:
      - "5173:5173"
    command: npm run dev
