version: "3"

services:
  backend:
    container_name: smart_elevator_backend_container
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate --fake-initial &&
            python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: smart_elevator_frontend_container
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev
