# Generated by Django 4.1.7 on 2023-04-01 09:53

from django.db import migrations, models


def create_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SystemConfig = apps.get_model("elevator", "SystemConfig")
    SystemConfig.objects.using(db_alias).create(no_elevators=2, no_floors=9)


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_elevators",
                    models.IntegerField(verbose_name="Number of Elevators"),
                ),
                ("no_floors", models.IntegerField(verbose_name="Number of Floors")),
            ],
        ),
        migrations.RunPython(create_types),
    ]
