# Generated by Django 4.1.7 on 2023-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_elevators",
                    models.IntegerField(verbose_name="Number of Elevators"),
                ),
                ("no_floors", models.IntegerField(verbose_name="Number of Floors")),
            ],
        ),
    ]
