# Generated by Django 4.1.7 on 2023-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0002_systemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfig",
            name="no_elevators",
            field=models.IntegerField(default=2, verbose_name="Number of Elevators"),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="no_floors",
            field=models.IntegerField(default=9, verbose_name="Number of Floors"),
        ),
    ]
