# Generated by Django 3.2.16 on 2023-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_remove_elevator_elevator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='floor_request',
            field=models.IntegerField(default=1, verbose_name='Floor Request'),
        ),
    ]
