# Generated by Django 4.1.7 on 2023-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0005_alter_elevator_floor_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="current_floor",
            field=models.IntegerField(default=1, verbose_name="Current Floor"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="elevator",
            name="elevator_id",
            field=models.IntegerField(default=1, verbose_name="Elevator ID"),
            preserve_default=False,
        ),
    ]
